config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'games#index'
  resources :games do 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  
  belongs_to :user

  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

 
  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = current_user.games.create(game_params)
    if @game.valid?
      redirect_to root_path
    else
      render :new, status: :uprocessable_entity
    end
  end

  def show
    @game = Game.find_by_id(params[:id])
    return render_not_found if @game.blank?
  end

  def edit
    @game = Game.find_by_id(params[:id])
      return render_not_found if @game.blank?
      return render_not_found(:forbidden) if @game.user != current_user
  end

  def update
    @game = Game.find_by_id(params[:id])
    return render_not_found if @game.blank?
    return render_not_found(:forbidden) if @game.user != current_user

    @game.update_attributes(game_params)
    if @game.valid?
      redirect_to root_path
    else
      return render :edit, status: :uprocessable_entity
    end
  end

  def destroy
    @game = Game.find_by_id(params[:id])
    return render_not_found if @game.blank?
    return render_not_found(:forbidden) if @game.user != current_user
    @game.destroy
    redirect_to root_path
  end

  private

  def game_params
    params.require(:game).permit(:name, :rating, :description, :picture)
  end

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize}", status: status
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h2 class="text-center">Welcome Haymus's Game Hub</h2>
<br />
<%# <% unless @games.empty? %>
  <ul class= "games">
    <% @games.each do |game| %>
        <li class= "booyah-box" >
          <h1 class= "text-center"><%= game.name %></h1>
          <% if game.picture.url %>
            <%= image_tag game.picture.url, class: 'img-fluid' %>
          <% end %>
          <i><%= game.rating %></i><br />
          <p><%= game.description %></p>
          <div class= "text-center">
            <% if game.user.present? %>
                <small><%= game.user.email %></small>
            <% end %> 
          </div>
        </li> 
    <% end %>
  </ul>
<%# <% end %> 

app/views/games/new.html.erb
<br />
<div class="booyah-box col-8 offset-2">
  <h1 class="text-center">Enter Your Game Details</h1>
  <%= simple_form_for @game do |f| %>
    <%= f.input :picture %>
    <%= f.input :name, placeholder: "Enter the name of Game" %>
    <%= f.input :rating, placeholder: "Enter rating out of 10 - Example 9 out of 10" %>
    <%= f.input :description, placeholder: "Enter a brief review of the game (max charaters 50)", :input_html => {:maxlength => 50, :size => 40} %>
    <br />
    <%= f.submit 'Post Review', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Haymus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "Haymus's Game Hub", root_path, class: 'navbar-brand' %>
 
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item active">
            <%= link_to '+Review Game', new_game_path, class: 'nav-link' %>
          </li>           
          <li class="nav-item">
            <%# <a><--Watch Your Favorite Streamer</a> %>
            <%= link_to href="https://twitch.tv" do %>
              <%= image_tag("Glitch_Purple_RGB.png", :alt => "image-logo", size: "25x25", class: "nav-logo") %>
            <% end %>
          </li>
          <%# <li class="nav-item active">
            <a><--Watch Your Favorite Streamer</a>
          </li>  %>
        </ul>
        <%# <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> %>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>